import { NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { INITIAL_PATIENTS } from '@/lib/mockData';

export async function POST(
  request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const patient = await request.json();

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]);
    const { width, height } = page.getSize();
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const margin = 50;
    let y = height - margin;

    const drawText = (text: string, font = helvetica, size = 12, color = rgb(0, 0, 0)) => {
      page.drawText(text, { x: margin, y, size, font, color });
      y -= (size + 5);
    };

    page.drawText('GOVERNMENT OF MAHARASHTRA | PUBLIC HEALTH DEPARTMENT', {
      x: margin, y, size: 14, font: helveticaBold, color: rgb(0.1, 0.3, 0.6)
    });
    y -= 25;
    
    page.drawText('SWASTHYA SETU - COMPLETE MEDICAL REPORT', {
      x: margin, y, size: 16, font: helveticaBold, color: rgb(0, 0, 0)
    });
    y -= 40;

    drawText('PATIENT DEMOGRAPHICS', helveticaBold, 14, rgb(0.2, 0.6, 0.6));
    y -= 5;
    drawText('Name: ' + patient.fullName);
    drawText('ABHA Number: ' + patient.abhaId);
    drawText('Age/Gender: ' + patient.age + ' / ' + patient.gender);
    drawText('Blood Group: ' + (patient.bloodGroup || 'N/A'));
    drawText('Phone: ' + patient.phone);
    drawText('Address: ' + (patient.village || 'N/A') + ', ' + (patient.taluka || 'N/A') + ', ' + (patient.district || 'N/A'));
    if (patient.emergencyContact) {
      drawText('Emergency Contact: ' + patient.emergencyContact.name + ' (' + patient.emergencyContact.phone + ')');
    }
    
    y -= 20;

    drawText('CLINICAL PROFILE & HISTORY', helveticaBold, 14, rgb(0.2, 0.6, 0.6));
    y -= 5;
    
    if (patient.isPregnant) {
      drawText('Pregnancy Status: Positive', helveticaBold, 12, rgb(0.8, 0.2, 0.2));
      drawText('High Risk: ' + (patient.isHighRiskPregnancy ? 'YES' : 'NO'));
    }
    
    if (patient.chronicConditions && patient.chronicConditions.length > 0) {
      drawText('Chronic Conditions: ' + patient.chronicConditions.join(', '));
    } else {
      drawText('Chronic Conditions: None reported.');
    }
    
    y -= 20;

    drawText('RECENT ENCOUNTERS & SCREENINGS', helveticaBold, 14, rgb(0.2, 0.6, 0.6));
    y -= 5;
    
    if (patient.encounters && patient.encounters.length > 0) {
      patient.encounters.slice(0, 3).forEach((enc: any) => {
        drawText('Date: ' + enc.date + ' | Facility: ' + enc.facilityName, helveticaBold, 11);
        drawText('Provider: ' + enc.providerName, helvetica, 11);
        if (enc.chiefComplaints) drawText('Complaints: ' + enc.chiefComplaints, helvetica, 11);
        if (enc.diagnosis) drawText('Diagnosis: ' + enc.diagnosis, helvetica, 11);
        
        if (enc.vitals) {
          const v = enc.vitals;
          drawText('Vitals: BP ' + v.systolicBp + '/' + v.diastolicBp + ' | HR ' + v.heartRate + ' | SpO2 ' + v.spO2 + '%', helvetica, 10, rgb(0.3, 0.3, 0.3));
        }
        y -= 10;
      });
    } else {
      drawText('No recent encounters on record.');
    }

    y = 50;
    page.drawLine({ start: { x: margin, y: y + 15 }, end: { x: width - margin, y: y + 15 }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
    page.drawText('Generated by SwasthyaSetu - Maharashtra ABDM Network', { x: margin, y, size: 10, font: helvetica, color: rgb(0.5, 0.5, 0.5) });
    page.drawText('Date: ' + new Date().toLocaleString('en-IN'), { x: width - margin - 150, y, size: 10, font: helvetica, color: rgb(0.5, 0.5, 0.5) });

    const pdfBytes = await pdfDoc.save();
    
    return new NextResponse(pdfBytes as any, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="Medical_Report_' + patient.abhaId + '.pdf"',
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return new NextResponse('Error generating PDF', { status: 500 });
  }
}

// Keep GET for fallback / backward compatibility
export async function GET(
  request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const params = await context.params;
    const id = params.id;
    const patient = INITIAL_PATIENTS.find(p => p.id === id || p.abhaId === id) || INITIAL_PATIENTS[0];
    
    // just re-route to the internal logic (using POST logic but hardcoding patient)
    const req = new Request('http://localhost', { method: 'POST', body: JSON.stringify(patient) });
    return await POST(req, context);
  } catch (error) {
    return new NextResponse('Error', { status: 500 });
  }
}
