import { Patient, Facility, Referral, DrugStockItem, OutbreakData } from './types';

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'fac-dh-pune',
    name: 'District Hospital Aundh, Pune',
    type: 'District Hospital',
    taluka: 'Haveli',
    district: 'Pune',
    phone: '+91-20-27280300',
    totalBeds: 350,
    occupiedBeds: 298,
    icuBedsTotal: 40,
    icuBedsOccupied: 36,
    ventilatorsTotal: 25,
    ventilatorsOccupied: 22,
    oxygenBedsTotal: 120,
    oxygenBedsOccupied: 104,
    availableSpecialists: ['Cardiology', 'Obstetrics & Gynaecology', 'Pediatrics', 'Orthopedics', 'General Surgery', 'Pulmonology', 'Anesthesiology'],
    lat: 18.5789,
    lng: 73.8077,
  },
  {
    id: 'fac-sassoon-pune',
    name: 'Sassoon General Hospital & BJMC, Pune',
    type: 'Medical College',
    taluka: 'Pune City',
    district: 'Pune',
    phone: '+91-20-26128000',
    totalBeds: 1200,
    occupiedBeds: 1110,
    icuBedsTotal: 120,
    icuBedsOccupied: 112,
    ventilatorsTotal: 80,
    ventilatorsOccupied: 74,
    oxygenBedsTotal: 450,
    oxygenBedsOccupied: 410,
    availableSpecialists: ['Cardiology', 'Neurology', 'Nephrology', 'Obstetrics & Gynaecology', 'Pediatrics', 'Trauma Surgery', 'Critical Care'],
    lat: 18.5284,
    lng: 73.8743,
  },
  {
    id: 'fac-rh-bhor',
    name: 'Bhor Rural Hospital (RH)',
    type: 'Rural Hospital',
    taluka: 'Bhor',
    district: 'Pune',
    phone: '+91-2113-222540',
    totalBeds: 50,
    occupiedBeds: 34,
    icuBedsTotal: 4,
    icuBedsOccupied: 3,
    ventilatorsTotal: 2,
    ventilatorsOccupied: 1,
    oxygenBedsTotal: 20,
    oxygenBedsOccupied: 14,
    availableSpecialists: ['General Medicine', 'Obstetrics & Gynaecology', 'Pediatrics'],
    lat: 18.1481,
    lng: 73.8443,
  },
  {
    id: 'fac-phc-velhe',
    name: 'Velhe Primary Health Centre (PHC)',
    type: 'PHC',
    taluka: 'Velhe',
    district: 'Pune',
    phone: '+91-2130-221230',
    totalBeds: 10,
    occupiedBeds: 6,
    icuBedsTotal: 0,
    icuBedsOccupied: 0,
    ventilatorsTotal: 0,
    ventilatorsOccupied: 0,
    oxygenBedsTotal: 4,
    oxygenBedsOccupied: 2,
    availableSpecialists: ['General Practitioner / Medical Officer'],
    lat: 18.2956,
    lng: 73.6358,
  },
  {
    id: 'fac-sc-ambavane',
    name: 'Ambavane Sub-Centre',
    type: 'Sub-Centre',
    taluka: 'Velhe',
    district: 'Pune',
    phone: '+91-9822019284',
    totalBeds: 2,
    occupiedBeds: 1,
    icuBedsTotal: 0,
    icuBedsOccupied: 0,
    ventilatorsTotal: 0,
    ventilatorsOccupied: 0,
    oxygenBedsTotal: 1,
    oxygenBedsOccupied: 0,
    availableSpecialists: ['ANM / ASHA Worker'],
    lat: 18.3245,
    lng: 73.5891,
  },
  {
    id: 'fac-dh-gadchiroli',
    name: 'General District Hospital, Gadchiroli',
    type: 'District Hospital',
    taluka: 'Gadchiroli',
    district: 'Gadchiroli',
    phone: '+91-7132-222145',
    totalBeds: 200,
    occupiedBeds: 182,
    icuBedsTotal: 16,
    icuBedsOccupied: 15,
    ventilatorsTotal: 8,
    ventilatorsOccupied: 7,
    oxygenBedsTotal: 70,
    oxygenBedsOccupied: 64,
    availableSpecialists: ['General Surgery', 'Obstetrics & Gynaecology', 'Pediatrics', 'Anesthesiology'],
    lat: 20.1809,
    lng: 80.0035,
  },
  {
    id: 'fac-dh-nashik',
    name: 'Nashik Civil Hospital',
    type: 'District Hospital',
    taluka: 'Nashik',
    district: 'Nashik',
    phone: '+91-253-2572534',
    totalBeds: 450,
    occupiedBeds: 395,
    icuBedsTotal: 50,
    icuBedsOccupied: 44,
    ventilatorsTotal: 30,
    ventilatorsOccupied: 26,
    oxygenBedsTotal: 180,
    oxygenBedsOccupied: 162,
    availableSpecialists: ['Cardiology', 'Obstetrics & Gynaecology', 'Pediatrics', 'Orthopedics', 'General Surgery', 'Critical Care'],
    lat: 20.0012,
    lng: 73.7845,
  }
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    abhaId: '91-4829-1049-3821',
    abhaAddress: 'priya.kamble@abdm',
    fullName: 'Priya Sachin Kamble',
    age: 26,
    gender: 'Female',
    phone: '9822451098',
    village: 'Ambavane',
    taluka: 'Velhe',
    district: 'Pune',
    bloodGroup: 'B Positive',
    isPregnant: true,
    gestationalWeeks: 34,
    isHighRiskPregnancy: true,
    chronicConditions: ['Gestational Hypertension', 'Mild Anemia'],
    emergencyContact: {
      name: 'Sachin Kamble',
      relation: 'Husband',
      phone: '9822451099',
    },
    encounters: [
      {
        id: 'enc-001-sc',
        patientId: 'pat-001',
        date: '2026-08-15',
        facilityName: 'Ambavane Sub-Centre',
        facilityType: 'Sub-Centre',
        providerName: 'Smt. Sunita Shinde (ASHA)',
        providerRole: 'ASHA Facilitator',
        chiefComplaints: ['Headache', 'Swelling in feet', 'Dizziness'],
        diagnosis: 'Suspected Pre-Eclampsia in 31st week',
        vitals: {
          systolicBp: 154,
          diastolicBp: 98,
          heartRate: 88,
          spO2: 97,
          respiratoryRate: 18,
          temperature: 36.8,
          bloodGlucose: 104,
          hemoglobin: 9.8,
          consciousLevel: 'alert',
          recordedAt: '2026-08-15T09:30:00Z',
        },
        prescriptions: [
          { medicineName: 'Iron & Folic Acid (IFA)', dosage: '100mg', frequency: '0-1-0', durationDays: 30, instructions: 'Take after afternoon meal with lemon water' },
          { medicineName: 'Calcium Carbonate', dosage: '500mg', frequency: '1-0-0', durationDays: 30, instructions: 'Take after breakfast' }
        ],
        notes: 'Flagged as High Risk Pregnancy (HRP). Escalated to Velhe PHC for medical officer evaluation.',
      },
      {
        id: 'enc-001-phc',
        patientId: 'pat-001',
        date: '2026-09-02',
        facilityName: 'Velhe Primary Health Centre (PHC)',
        facilityType: 'PHC',
        providerName: 'Dr. Rajesh Deshmukh',
        providerRole: 'Medical Officer MBBS',
        chiefComplaints: ['Persistent blurred vision', 'Epigastric discomfort', 'Severe headache'],
        diagnosis: 'Severe Pre-eclampsia in G3P2 at 34 weeks',
        icd10Code: 'O14.1',
        vitals: {
          systolicBp: 178,
          diastolicBp: 114,
          heartRate: 106,
          spO2: 94,
          respiratoryRate: 24,
          temperature: 37.1,
          bloodGlucose: 118,
          hemoglobin: 9.2,
          consciousLevel: 'alert',
          recordedAt: '2026-09-02T11:15:00Z',
        },
        prescriptions: [
          { medicineName: 'Labetalol', dosage: '100mg', frequency: '1-0-1', durationDays: 7, instructions: 'Take strictly with water' },
          { medicineName: 'Magnesium Sulphate (Loading Dose)', dosage: '4g IV + 10g IM', frequency: 'Stat', durationDays: 1, instructions: 'Administered at PHC before transfer' }
        ],
        labReports: [
          {
            id: 'lab-001',
            testName: 'Urine Protein Dipstick',
            result: '3+ (Severe Proteinuria)',
            normalRange: 'Nil / Trace',
            isAbnormal: true,
            date: '2026-09-02',
            labFacility: 'Velhe PHC Lab',
          },
          {
            id: 'lab-002',
            testName: 'Platelet Count',
            result: '1,10,000 /uL',
            normalRange: '1,50,000 - 4,50,000',
            isAbnormal: true,
            date: '2026-09-02',
            labFacility: 'Velhe PHC Lab',
          }
        ],
        notes: 'Pre-eclampsia progressing towards Eclampsia risk. Emergency Red Triage referral generated to District Hospital Aundh Pune for emergency NICU + OB-GYN intervention.',
        referralId: 'ref-101',
      }
    ],
    activeReferralId: 'ref-101',
  },
  {
    id: 'pat-002',
    abhaId: '82-9012-3344-7712',
    abhaAddress: 'tukaram.shirke@abdm',
    fullName: 'Tukaram Pandurang Shirke',
    age: 62,
    gender: 'Male',
    phone: '9423187290',
    village: 'Bhor Rural',
    taluka: 'Bhor',
    district: 'Pune',
    bloodGroup: 'O Positive',
    chronicConditions: ['Type 2 Diabetes Mellitus', 'Coronary Artery Disease'],
    emergencyContact: {
      name: 'Ganesh Shirke',
      relation: 'Son',
      phone: '9423187291',
    },
    encounters: [
      {
        id: 'enc-002-rh',
        patientId: 'pat-002',
        date: '2026-09-04',
        facilityName: 'Bhor Rural Hospital (RH)',
        facilityType: 'Rural Hospital',
        providerName: 'Dr. Meera Gaikwad',
        providerRole: 'Casualty Medical Officer',
        chiefComplaints: ['Acute retrosternal crushing chest pain radiating to left jaw', 'Profuse diaphoresis', 'Breathlessness'],
        diagnosis: 'Acute Anterior Wall ST-Elevation Myocardial Infarction (STEMI)',
        icd10Code: 'I21.0',
        vitals: {
          systolicBp: 88,
          diastolicBp: 56,
          heartRate: 118,
          spO2: 89,
          respiratoryRate: 26,
          temperature: 36.4,
          bloodGlucose: 240,
          consciousLevel: 'alert',
          recordedAt: '2026-09-04T13:40:00Z',
        },
        prescriptions: [
          { medicineName: 'Aspirin (Dispersible)', dosage: '300mg', frequency: 'Stat', durationDays: 1, instructions: 'Chewed immediately' },
          { medicineName: 'Clopidogrel', dosage: '300mg', frequency: 'Stat', durationDays: 1, instructions: 'Given with water' },
          { medicineName: 'Atorvastatin', dosage: '80mg', frequency: 'Stat', durationDays: 1, instructions: 'Night dose' }
        ],
        notes: 'ECG demonstrates ST elevation in V1-V4. Cardiogenic shock risk (SBP 88 mmHg, SpO2 89%). High-priority RED referral to Sassoon Cath Lab / ICU.',
        referralId: 'ref-102',
      }
    ],
    activeReferralId: 'ref-102',
  },
  {
    id: 'pat-003',
    abhaId: '54-1920-8833-2211',
    abhaAddress: 'kavita.jadhav@abdm',
    fullName: 'Kavita Namdev Jadhav',
    age: 38,
    gender: 'Female',
    phone: '9765412093',
    village: 'Pasali',
    taluka: 'Velhe',
    district: 'Pune',
    bloodGroup: 'A Positive',
    chronicConditions: ['Bronchial Asthma'],
    emergencyContact: {
      name: 'Namdev Jadhav',
      relation: 'Husband',
      phone: '9765412094',
    },
    encounters: [
      {
        id: 'enc-003-phc',
        patientId: 'pat-003',
        date: '2026-09-01',
        facilityName: 'Velhe Primary Health Centre (PHC)',
        facilityType: 'PHC',
        providerName: 'Dr. Rajesh Deshmukh',
        providerRole: 'Medical Officer',
        chiefComplaints: ['High fever for 4 days', 'Joint pain', 'Petechial rash on forearms'],
        diagnosis: 'Acute Dengue Fever with Thrombocytopenia',
        icd10Code: 'A90',
        vitals: {
          systolicBp: 112,
          diastolicBp: 74,
          heartRate: 92,
          spO2: 96,
          respiratoryRate: 19,
          temperature: 38.9,
          bloodGlucose: 108,
          hemoglobin: 12.4,
          consciousLevel: 'alert',
          recordedAt: '2026-09-01T10:00:00Z',
        },
        prescriptions: [
          { medicineName: 'Paracetamol', dosage: '650mg', frequency: '1-1-1', durationDays: 5, instructions: 'SOS for fever > 100°F. Do NOT take Brufen/Aspirin.' },
          { medicineName: 'Oral Rehydration Salts (ORS)', dosage: '1 sachet in 1L water', frequency: 'Ad libitum', durationDays: 5, instructions: 'Maintain abundant oral hydration' }
        ],
        labReports: [
          {
            id: 'lab-003',
            testName: 'Dengue NS1 Antigen Rapid',
            result: 'POSITIVE',
            normalRange: 'Negative',
            isAbnormal: true,
            date: '2026-09-01',
            labFacility: 'Velhe PHC Lab',
          },
          {
            id: 'lab-004',
            testName: 'Platelet Count',
            result: '82,000 /uL',
            normalRange: '1,50,000 - 4,50,000',
            isAbnormal: true,
            date: '2026-09-01',
            labFacility: 'Velhe PHC Lab',
          }
        ],
        notes: 'Yellow triage referral for close platelet monitoring and fluid management at Bhor Rural Hospital.',
        referralId: 'ref-103',
      }
    ],
    activeReferralId: 'ref-103',
  },
  {
    id: 'pat-004',
    abhaId: '76-3391-4455-6677',
    abhaAddress: 'arjun.chavan@abdm',
    fullName: 'Master Arjun Sanjay Chavan',
    age: 4,
    gender: 'Male',
    phone: '9890123456',
    village: 'Kelawade',
    taluka: 'Bhor',
    district: 'Pune',
    bloodGroup: 'O Positive',
    chronicConditions: [],
    emergencyContact: {
      name: 'Sanjay Chavan',
      relation: 'Father',
      phone: '9890123456',
    },
    encounters: [
      {
        id: 'enc-004-sc',
        patientId: 'pat-004',
        date: '2026-09-03',
        facilityName: 'Kelawade Sub-Centre',
        facilityType: 'Sub-Centre',
        providerName: 'Smt. Vandana More (ASHA)',
        providerRole: 'ASHA Facilitator',
        chiefComplaints: ['Loose motions > 6 times in 12 hours', 'Lethargic', 'Sunken eyes', 'Vomiting'],
        diagnosis: 'Acute Gastroenteritis with Moderate-to-Severe Dehydration',
        vitals: {
          systolicBp: 86,
          diastolicBp: 52,
          heartRate: 134,
          spO2: 95,
          respiratoryRate: 32,
          temperature: 37.8,
          consciousLevel: 'voice',
          recordedAt: '2026-09-03T14:20:00Z',
        },
        prescriptions: [
          { medicineName: 'Zinc Sulfate Syrup', dosage: '20mg (5ml)', frequency: '0-1-0', durationDays: 14, instructions: 'Give once daily for 14 days' },
          { medicineName: 'ORS Solution', dosage: 'Frequent sips', frequency: 'Continuous', durationDays: 3, instructions: 'Give after every stool' }
        ],
        notes: 'Pediatric dehydration, altered sensorium (responds to voice). Urgent referral initiated to Bhor RH / District Hospital Pediatric Ward.',
        referralId: 'ref-104',
      }
    ],
    activeReferralId: 'ref-104',
  }
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref-101',
    tokenCode: 'MH-REF-2026-9842',
    patientId: 'pat-001',
    patientName: 'Priya Sachin Kamble',
    patientAbha: '91-4829-1049-3821',
    patientAge: 26,
    patientGender: 'Female',
    referringFacility: 'Velhe Primary Health Centre (PHC)',
    targetFacility: 'District Hospital Aundh, Pune',
    specialtyRequired: 'Obstetrics & Gynaecology / NICU',
    referralReason: 'Severe Pre-eclampsia at 34 weeks, SBP 178 mmHg, Urine Albumin 3+, imminent eclampsia risk.',
    triagePriority: 'red',
    triageScore: 8,
    triageReasons: [
      'Hypertensive Crisis (SBP 178 mmHg / DBP 114 mmHg)',
      'Tachypnea (RR 24 /min)',
      'Borderline SpO2 94%',
      'Severe Proteinuria 3+'
    ],
    vitalsAtReferral: {
      systolicBp: 178,
      diastolicBp: 114,
      heartRate: 106,
      spO2: 94,
      respiratoryRate: 24,
      temperature: 37.1,
      consciousLevel: 'alert',
      recordedAt: '2026-09-02T11:15:00Z',
    },
    referringDoctorName: 'Dr. Rajesh Deshmukh (Reg: MMC-2014/08/3412)',
    createdAt: '2026-09-04T13:10:00Z',
    status: 'PENDING',
    ambulanceDispatched: true,
    assignedBed: 'ICU-Maternity Bed #04 (Reserved)',
    qrPayload: JSON.stringify({
      token: 'MH-REF-2026-9842',
      abha: '91-4829-1049-3821',
      name: 'Priya Sachin Kamble',
      triage: 'RED',
      target: 'District Hospital Aundh, Pune',
      specialty: 'Obstetrics & Gynaecology / NICU',
      vitals: '178/114 mmHg, SpO2 94%, HR 106',
      alsAmbulance: 'MH-12-HE-1082',
    })
  },
  {
    id: 'ref-102',
    tokenCode: 'MH-REF-2026-9843',
    patientId: 'pat-002',
    patientName: 'Tukaram Pandurang Shirke',
    patientAbha: '82-9012-3344-7712',
    patientAge: 62,
    patientGender: 'Male',
    referringFacility: 'Bhor Rural Hospital (RH)',
    targetFacility: 'Sassoon General Hospital & BJMC, Pune',
    specialtyRequired: 'Cardiology (Cath Lab / Emergency PCI)',
    referralReason: 'Acute STEMI, Cardiogenic Shock (BP 88/56), severe retrosternal pain, SpO2 89%.',
    triagePriority: 'red',
    triageScore: 9,
    triageReasons: [
      'Hypotension / Shock risk (SBP 88 mmHg)',
      'Critical Hypoxia (SpO2 89%)',
      'Severe Tachycardia (HR 118 bpm)',
      'Severe Tachypnea (RR 26 /min)'
    ],
    vitalsAtReferral: {
      systolicBp: 88,
      diastolicBp: 56,
      heartRate: 118,
      spO2: 89,
      respiratoryRate: 26,
      temperature: 36.4,
      consciousLevel: 'alert',
      recordedAt: '2026-09-04T13:40:00Z',
    },
    referringDoctorName: 'Dr. Meera Gaikwad (Reg: MMC-2018/02/1129)',
    createdAt: '2026-09-04T13:45:00Z',
    status: 'ACCEPTED',
    ambulanceDispatched: true,
    assignedBed: 'Cardiac CCU Bed #08',
    qrPayload: JSON.stringify({
      token: 'MH-REF-2026-9843',
      abha: '82-9012-3344-7712',
      name: 'Tukaram Pandurang Shirke',
      triage: 'RED',
      target: 'Sassoon General Hospital & BJMC, Pune',
      specialty: 'Cardiology',
      vitals: '88/56 mmHg, SpO2 89%, HR 118',
      alsAmbulance: 'MH-12-EM-1085',
    })
  },
  {
    id: 'ref-103',
    tokenCode: 'MH-REF-2026-9844',
    patientId: 'pat-003',
    patientName: 'Kavita Namdev Jadhav',
    patientAbha: '54-1920-8833-2211',
    patientAge: 38,
    patientGender: 'Female',
    referringFacility: 'Velhe Primary Health Centre (PHC)',
    targetFacility: 'Bhor Rural Hospital (RH)',
    specialtyRequired: 'General Medicine / Blood Bank Support',
    referralReason: 'Dengue NS1 positive with rapid platelet drop to 82,000, high continuous fever, petechiae.',
    triagePriority: 'yellow',
    triageScore: 4,
    triageReasons: [
      'High Pyrexia (Temp 38.9°C)',
      'Rapid platelet consumption',
      'Mild Tachycardia (HR 92 bpm)'
    ],
    vitalsAtReferral: {
      systolicBp: 112,
      diastolicBp: 74,
      heartRate: 92,
      spO2: 96,
      respiratoryRate: 19,
      temperature: 38.9,
      consciousLevel: 'alert',
      recordedAt: '2026-09-01T10:00:00Z',
    },
    referringDoctorName: 'Dr. Rajesh Deshmukh',
    createdAt: '2026-09-04T11:20:00Z',
    status: 'ACCEPTED',
    ambulanceDispatched: false,
    assignedBed: 'Female Medical Ward Bed #12',
    qrPayload: JSON.stringify({
      token: 'MH-REF-2026-9844',
      abha: '54-1920-8833-2211',
      name: 'Kavita Namdev Jadhav',
      triage: 'YELLOW',
      target: 'Bhor Rural Hospital (RH)',
      specialty: 'General Medicine',
      vitals: '112/74 mmHg, Platelets 82k',
    })
  },
  {
    id: 'ref-104',
    tokenCode: 'MH-REF-2026-9845',
    patientId: 'pat-004',
    patientName: 'Master Arjun Sanjay Chavan',
    patientAbha: '76-3391-4455-6677',
    patientAge: 4,
    patientGender: 'Male',
    referringFacility: 'Ambavane Sub-Centre',
    targetFacility: 'Bhor Rural Hospital (RH)',
    specialtyRequired: 'Pediatrics',
    referralReason: 'Pediatric dehydration due to acute gastroenteritis, sunken eyes, drowsy sensorium.',
    triagePriority: 'red',
    triageScore: 8,
    triageReasons: [
      'Severe Tachycardia (HR 134 bpm)',
      'Severe Tachypnea (RR 32 /min)',
      'Pediatric Hypotension (SBP 86 mmHg)',
      'Sensorium: Responds only to voice'
    ],
    vitalsAtReferral: {
      systolicBp: 86,
      diastolicBp: 52,
      heartRate: 134,
      spO2: 95,
      respiratoryRate: 32,
      temperature: 37.8,
      consciousLevel: 'voice',
      recordedAt: '2026-09-03T14:20:00Z',
    },
    referringDoctorName: 'Smt. Vandana More (ASHA / Sub-Centre Incharge)',
    createdAt: '2026-09-04T14:10:00Z',
    status: 'PENDING',
    ambulanceDispatched: true,
    assignedBed: 'Pediatric High Dependency Bed #03',
    qrPayload: JSON.stringify({
      token: 'MH-REF-2026-9845',
      abha: '76-3391-4455-6677',
      name: 'Master Arjun Sanjay Chavan',
      triage: 'RED',
      target: 'Bhor Rural Hospital (RH)',
      specialty: 'Pediatrics',
      vitals: '86/52 mmHg, HR 134, RR 32',
    })
  }
];

export const INITIAL_DRUG_STOCKS: DrugStockItem[] = [
  {
    id: 'stk-001',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe PHC',
    drugName: 'Anti-Snake Venom (ASV Polyvalent Lyophilized)',
    category: 'Critical Lifesaving',
    currentStock: 4,
    bufferStock: 20,
    unit: 'Vials (10ml)',
    batchNumber: 'ASV-MH-2026-042',
    expiryDate: '2027-12-31',
    status: 'CRITICAL', // Low stock alert!
  },
  {
    id: 'stk-002',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe PHC',
    drugName: 'Anti-Rabies Vaccine (ARV Purified Vero Cell)',
    category: 'Vaccine',
    currentStock: 12,
    bufferStock: 30,
    unit: 'Doses',
    batchNumber: 'ARV-2026-991',
    expiryDate: '2027-08-30',
    status: 'LOW',
  },
  {
    id: 'stk-003',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe PHC',
    drugName: 'Oxytocin Injection IP (10 IU/ml)',
    category: 'Maternal Health',
    currentStock: 45,
    bufferStock: 50,
    unit: 'Ampoules',
    batchNumber: 'OXY-MH-8812',
    expiryDate: '2027-06-30',
    status: 'OPTIMAL',
  },
  {
    id: 'stk-004',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe PHC',
    drugName: 'Magnesium Sulphate 50% Inj',
    category: 'Maternal Health',
    currentStock: 8,
    bufferStock: 25,
    unit: 'Ampoules',
    batchNumber: 'MGSO4-4412',
    expiryDate: '2028-01-31',
    status: 'CRITICAL',
  },
  {
    id: 'stk-005',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe PHC',
    drugName: 'Medical Oxygen D-Type Cylinders (46.7L)',
    category: 'Emergency Gas',
    currentStock: 3,
    bufferStock: 8,
    unit: 'Cylinders',
    batchNumber: 'O2-BHOR-09',
    expiryDate: 'N/A',
    status: 'LOW',
  },
  {
    id: 'stk-006',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    drugName: 'Anti-Snake Venom (ASV Polyvalent Lyophilized)',
    category: 'Critical Lifesaving',
    currentStock: 180,
    bufferStock: 80,
    unit: 'Vials (10ml)',
    batchNumber: 'ASV-MH-2026-118',
    expiryDate: '2028-03-31',
    status: 'OPTIMAL',
  },
  {
    id: 'stk-007',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    drugName: 'Human Insulin Regular (100 IU/ml)',
    category: 'Critical Lifesaving',
    currentStock: 95,
    bufferStock: 50,
    unit: 'Vials',
    batchNumber: 'INS-R-9021',
    expiryDate: '2027-11-30',
    status: 'OPTIMAL',
  },
  {
    id: 'stk-008',
    facilityId: 'fac-dh-gadchiroli',
    facilityName: 'District Hospital Gadchiroli',
    drugName: 'Artemether + Lumefantrine Inj (Severe Malaria)',
    category: 'Critical Lifesaving',
    currentStock: 14,
    bufferStock: 60,
    unit: 'Ampoules',
    batchNumber: 'ART-GAD-302',
    expiryDate: '2027-04-30',
    status: 'CRITICAL',
  }
];

export const INITIAL_OUTBREAKS: OutbreakData[] = [
  {
    id: 'out-001',
    district: 'Pune',
    taluka: 'Haveli & Velhe',
    diseaseName: 'Dengue',
    activeCases: 142,
    weeklyChangePercent: 28.5,
    riskLevel: 'HIGH',
    primaryHotspotVillage: 'Velhe Budruk & Khanapur',
    subCentresAffected: 9,
    reportedDate: '2026-09-04',
  },
  {
    id: 'out-002',
    district: 'Gadchiroli',
    taluka: 'Bhamragad & Dhanora',
    diseaseName: 'Malaria',
    activeCases: 98,
    weeklyChangePercent: 15.2,
    riskLevel: 'HIGH',
    primaryHotspotVillage: 'Arewada & Laheri',
    subCentresAffected: 14,
    reportedDate: '2026-09-04',
  },
  {
    id: 'out-003',
    district: 'Nashik',
    taluka: 'Trimbakeshwar',
    diseaseName: 'Acute Diarrheal Disease',
    activeCases: 54,
    weeklyChangePercent: -8.0,
    riskLevel: 'MODERATE',
    primaryHotspotVillage: 'Harsul',
    subCentresAffected: 4,
    reportedDate: '2026-09-03',
  },
  {
    id: 'out-004',
    district: 'Thane',
    taluka: 'Bhiwandi & Shahapur',
    diseaseName: 'Leptospirosis',
    activeCases: 23,
    weeklyChangePercent: 4.5,
    riskLevel: 'MODERATE',
    primaryHotspotVillage: 'Khadvali',
    subCentresAffected: 3,
    reportedDate: '2026-09-02',
  },
  {
    id: 'out-005',
    district: 'Chhatrapati Sambhajinagar',
    taluka: 'Paithan',
    diseaseName: 'Chikungunya',
    activeCases: 39,
    weeklyChangePercent: 11.4,
    riskLevel: 'MODERATE',
    primaryHotspotVillage: 'Bidkin',
    subCentresAffected: 5,
    reportedDate: '2026-09-04',
  }
];

export const INITIAL_FOLLOWUPS: import('./types').FollowUpTask[] = [
  {
    id: 'flw-01',
    patientId: 'pat-001',
    patientName: 'Priya Sachin Kamble',
    patientPhone: '9822451098',
    category: 'Maternal ANC',
    dueDate: '2026-09-06',
    status: 'DUE',
    notes: '34-week Pre-eclampsia BP monitoring & USG Doppler follow-up',
    assignedAshaName: 'Smt. Sunita Shinde',
  },
  {
    id: 'flw-02',
    patientId: 'pat-004',
    patientName: 'Master Arjun Sanjay Chavan',
    patientPhone: '9890123456',
    category: 'Child Immunization',
    dueDate: '2026-09-03',
    status: 'OVERDUE',
    notes: 'DPT Booster & Measles-Rubella (MR) Dose 2 overdue by 1 day',
    assignedAshaName: 'Smt. Vandana More',
  },
  {
    id: 'flw-03',
    patientId: 'pat-003',
    patientName: 'Kavita Namdev Jadhav',
    patientPhone: '9765412093',
    category: 'Post-Referral Check',
    dueDate: '2026-09-07',
    status: 'DUE',
    notes: 'Dengue post-discharge platelet count reconciliation',
    assignedAshaName: 'Smt. Sunita Shinde',
  },
  {
    id: 'flw-04',
    patientId: 'pat-002',
    patientName: 'Tukaram Pandurang Shirke',
    patientPhone: '9423187290',
    category: 'Hypertension Review',
    dueDate: '2026-09-05',
    status: 'DUE',
    notes: 'Cardiac post-STEMI dual anti-platelet compliance verification',
    assignedAshaName: 'Smt. Vandana More',
  },
];

export const INITIAL_PREDICTIONS: import('./types').PredictiveForecast[] = [
  {
    facilityName: 'District Hospital Aundh, Pune',
    forecastDay: 'Next 7 Days (05-11 Sep)',
    expectedOpdLoad: 4120,
    expectedEmergencyAdmissions: 280,
    predictedBedStrainPercent: 94,
    riskAlert: 'Critical ICU bed deficit anticipated due to seasonal Dengue/Fever surge.',
  },
  {
    facilityName: 'Sassoon General Hospital & BJMC, Pune',
    forecastDay: 'Next 7 Days (05-11 Sep)',
    expectedOpdLoad: 12400,
    expectedEmergencyAdmissions: 950,
    predictedBedStrainPercent: 98,
    riskAlert: 'Tertiary Trauma & CCU at peak capacity; recommend diverting routine surgical referrals.',
  },
  {
    facilityName: 'Bhor Rural Hospital (RH)',
    forecastDay: 'Next 7 Days (05-11 Sep)',
    expectedOpdLoad: 890,
    expectedEmergencyAdmissions: 42,
    predictedBedStrainPercent: 68,
    riskAlert: 'Capacity available; can absorb moderate pediatric & maternal referrals.',
  },
  {
    facilityName: 'Velhe Primary Health Centre (PHC)',
    forecastDay: 'Next 7 Days (05-11 Sep)',
    expectedOpdLoad: 610,
    expectedEmergencyAdmissions: 18,
    predictedBedStrainPercent: 55,
    riskAlert: 'Anti-Snake Venom (ASV) buffer at risk of total stockout within 48 hours.',
  },
];

