import {
  SpecialistOnDuty,
  HospitalBedSlot,
  EmergencyWalkIn,
  FacilityDischargeRecord,
  HospitalBloodStock,
  TamperEvidentAuditBlock,
} from './types';

// =========================================================================
// 1. SPECIALIST ON-CALL ROSTER (TODAY'S SHIFT)
// =========================================================================

export const INITIAL_SPECIALISTS_ON_DUTY: SpecialistOnDuty[] = [
  {
    id: 'spec-duty-01',
    name: 'Dr. Ananya Kulkarni',
    qualification: 'MD (Emergency Medicine & Critical Care)',
    specialty: 'Trauma & Emergency Care',
    department: 'Casualty / ER',
    status: 'ON_DUTY',
    phone: '+91-9823091823',
    shift: 'MORNING',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 4,
  },
  {
    id: 'spec-duty-02',
    name: 'Dr. Vikramaditya Salunkhe',
    qualification: 'DM (Cardiology), MD (Gen Med)',
    specialty: 'Cardiology',
    department: 'ICU',
    status: 'ON_DUTY',
    phone: '+91-9822144321',
    shift: '24_HOUR_CALL',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 2,
  },
  {
    id: 'spec-duty-03',
    name: 'Dr. Sneha Deshpande',
    qualification: 'MS (Obstetrics & Gynaecology), DGO',
    specialty: 'Obstetrics & Gynaecology',
    department: 'Maternity / NICU',
    status: 'IN_SURGERY',
    phone: '+91-9822155678',
    shift: 'MORNING',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 3,
  },
  {
    id: 'spec-duty-04',
    name: 'Dr. Milind Gadgil',
    qualification: 'MS (Orthopaedics), MCh (Trauma)',
    specialty: 'Orthopedics',
    department: 'Surgical Suite',
    status: 'ON_DUTY',
    phone: '+91-9822166789',
    shift: 'MORNING',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 1,
  },
  {
    id: 'spec-duty-05',
    name: 'Dr. Radhika Joshi',
    qualification: 'MD (Pediatrics), DCH',
    specialty: 'Pediatrics',
    department: 'Maternity / NICU',
    status: 'ON_CALL',
    phone: '+91-9822177890',
    shift: 'EVENING',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 2,
  },
  {
    id: 'spec-duty-06',
    name: 'Dr. Prashant Shinde',
    qualification: 'MD (Anesthesiology)',
    specialty: 'Anesthesiology',
    department: 'ICU',
    status: 'ON_DUTY',
    phone: '+91-9822188901',
    shift: '24_HOUR_CALL',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 5,
  },
  {
    id: 'spec-duty-07',
    name: 'Dr. Sanjay Wagh',
    qualification: 'MS (General Surgery)',
    specialty: 'General Surgery',
    department: 'Surgical Suite',
    status: 'OFF_DUTY',
    phone: '+91-9822199012',
    shift: 'NIGHT',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    activeCasesCount: 0,
  },
];

// =========================================================================
// 2. DEPARTMENT-WISE BED MATRIX SLOTS
// =========================================================================

export const INITIAL_HOSPITAL_BED_SLOTS: HospitalBedSlot[] = [
  // --- ICU WARD (8 Beds) ---
  {
    bedId: 'bed-icu-01',
    bedNumber: 'ICU-B01',
    wardName: 'Critical Care ICU Wing A',
    department: 'ICU',
    status: 'OCCUPIED',
    patientId: 'pat-001',
    patientName: 'Priya Sachin Kamble',
    patientAbha: '91-4829-1049-3821',
    triagePriority: 'red',
    assignedAt: '2026-09-12T08:30:00Z',
    attendingSpecialist: 'Dr. Sneha Deshpande',
    specialtyRequired: 'Obstetrics & Gynaecology',
    referralId: 'ref-101',
  },
  {
    bedId: 'bed-icu-02',
    bedNumber: 'ICU-B02',
    wardName: 'Critical Care ICU Wing A',
    department: 'ICU',
    status: 'OCCUPIED',
    patientId: 'pat-002',
    patientName: 'Dnyaneshwar Shinde',
    patientAbha: '91-3829-5028-1192',
    triagePriority: 'red',
    assignedAt: '2026-09-13T10:15:00Z',
    attendingSpecialist: 'Dr. Vikramaditya Salunkhe',
    specialtyRequired: 'Cardiology',
    referralId: 'ref-102',
  },
  {
    bedId: 'bed-icu-03',
    bedNumber: 'ICU-B03',
    wardName: 'Critical Care ICU Wing A',
    department: 'ICU',
    status: 'OCCUPIED',
    patientId: 'pat-walkin-01',
    patientName: 'Rameshwar Pawar',
    patientAbha: '91-1122-3344-5566',
    triagePriority: 'red',
    assignedAt: '2026-09-14T14:20:00Z',
    attendingSpecialist: 'Dr. Prashant Shinde',
    specialtyRequired: 'Trauma & Emergency Care',
  },
  {
    bedId: 'bed-icu-04',
    bedNumber: 'ICU-B04',
    wardName: 'Critical Care ICU Wing A',
    department: 'ICU',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-icu-05',
    bedNumber: 'ICU-B05',
    wardName: 'Critical Care ICU Wing B',
    department: 'ICU',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-icu-06',
    bedNumber: 'ICU-B06',
    wardName: 'Critical Care ICU Wing B',
    department: 'ICU',
    status: 'MAINTENANCE',
  },

  // --- CASUALTY / ER (6 Beds) ---
  {
    bedId: 'bed-cas-01',
    bedNumber: 'ER-BAY-01',
    wardName: 'Trauma Resuscitation Bay',
    department: 'Casualty / ER',
    status: 'OCCUPIED',
    patientId: 'pat-006',
    patientName: 'Santosh Baban Khairnar',
    patientAbha: '71-9922-3344-5566',
    triagePriority: 'red',
    assignedAt: '2026-09-15T09:00:00Z',
    attendingSpecialist: 'Dr. Ananya Kulkarni',
    specialtyRequired: 'Trauma & Emergency Care',
  },
  {
    bedId: 'bed-cas-02',
    bedNumber: 'ER-BAY-02',
    wardName: 'Trauma Resuscitation Bay',
    department: 'Casualty / ER',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-cas-03',
    bedNumber: 'ER-BAY-03',
    wardName: 'Observation Ward 1',
    department: 'Casualty / ER',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-cas-04',
    bedNumber: 'ER-BAY-04',
    wardName: 'Observation Ward 1',
    department: 'Casualty / ER',
    status: 'AVAILABLE',
  },

  // --- MATERNITY / NICU (8 Beds) ---
  {
    bedId: 'bed-mat-01',
    bedNumber: 'MAT-B01',
    wardName: 'Labour & High-Risk Obstetric Ward',
    department: 'Maternity / NICU',
    status: 'OCCUPIED',
    patientId: 'pat-005',
    patientName: 'Sunanda Vilas Jagtap',
    patientAbha: '91-5522-1144-8899',
    triagePriority: 'yellow',
    assignedAt: '2026-09-13T11:45:00Z',
    attendingSpecialist: 'Dr. Sneha Deshpande',
    specialtyRequired: 'Obstetrics & Gynaecology',
  },
  {
    bedId: 'bed-mat-02',
    bedNumber: 'MAT-B02',
    wardName: 'Labour & High-Risk Obstetric Ward',
    department: 'Maternity / NICU',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-mat-03',
    bedNumber: 'MAT-B03',
    wardName: 'Postnatal Ward A',
    department: 'Maternity / NICU',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-mat-04',
    bedNumber: 'NICU-B01',
    wardName: 'Neonatal Intensive Care Unit',
    department: 'Maternity / NICU',
    status: 'AVAILABLE',
  },

  // --- GENERAL WARD (12 Beds) ---
  {
    bedId: 'bed-gen-01',
    bedNumber: 'GEN-M-01',
    wardName: 'Male Medical Ward',
    department: 'General Ward',
    status: 'OCCUPIED',
    patientId: 'pat-003',
    patientName: 'Savita Namdev Jadhav',
    patientAbha: '91-9988-7766-5544',
    triagePriority: 'yellow',
    assignedAt: '2026-09-14T10:00:00Z',
    attendingSpecialist: 'Dr. Ananya Kulkarni',
    specialtyRequired: 'General Medicine',
  },
  {
    bedId: 'bed-gen-02',
    bedNumber: 'GEN-M-02',
    wardName: 'Male Medical Ward',
    department: 'General Ward',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-gen-03',
    bedNumber: 'GEN-F-01',
    wardName: 'Female Medical Ward',
    department: 'General Ward',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-gen-04',
    bedNumber: 'GEN-F-02',
    wardName: 'Female Medical Ward',
    department: 'General Ward',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-gen-05',
    bedNumber: 'GEN-ORTHO-01',
    wardName: 'Orthopedic Ward',
    department: 'General Ward',
    status: 'AVAILABLE',
  },
  {
    bedId: 'bed-gen-06',
    bedNumber: 'GEN-ORTHO-02',
    wardName: 'Orthopedic Ward',
    department: 'General Ward',
    status: 'AVAILABLE',
  },
];

// =========================================================================
// 3. EMERGENCY WALK-INS (CASUALTY ARRIVALS)
// =========================================================================

export const INITIAL_EMERGENCY_WALKINS: EmergencyWalkIn[] = [
  {
    id: 'walkin-001',
    tokenCode: 'DH-CAS-901',
    fullName: 'Rameshwar Pawar',
    age: 52,
    gender: 'Male',
    phone: '9822199088',
    abhaId: '91-1122-3344-5566',
    chiefComplaint: 'Severe crush injury to right lower limb after tractor rollover, heavy arterial bleeding',
    triagePriority: 'red',
    vitals: {
      systolicBp: 85,
      diastolicBp: 55,
      heartRate: 128,
      spO2: 91,
      respiratoryRate: 26,
      temperature: 36.4,
      consciousLevel: 'voice',
      recordedAt: '2026-09-15T09:30:00Z',
    },
    arrivalTime: '2026-09-15T09:30:00Z',
    status: 'ADMITTED',
    assignedDoctorName: 'Dr. Ananya Kulkarni',
    assignedBedId: 'bed-icu-03',
  },
  {
    id: 'walkin-002',
    tokenCode: 'DH-CAS-902',
    fullName: 'Shantabai Gawande',
    age: 68,
    gender: 'Female',
    phone: '9822199099',
    abhaId: '91-7788-9900-1122',
    chiefComplaint: 'Acute chest tightness radiating to jaw, profuse diaphoresis for 45 mins',
    triagePriority: 'red',
    vitals: {
      systolicBp: 175,
      diastolicBp: 105,
      heartRate: 110,
      spO2: 88,
      respiratoryRate: 24,
      temperature: 37.0,
      consciousLevel: 'alert',
      recordedAt: '2026-09-15T11:15:00Z',
    },
    arrivalTime: '2026-09-15T11:15:00Z',
    status: 'TRIAGED',
  },
  {
    id: 'walkin-003',
    tokenCode: 'DH-CAS-903',
    fullName: 'Aniket Deepak More',
    age: 19,
    gender: 'Male',
    phone: '9822199100',
    chiefComplaint: 'Two-wheeler skid injury, deep laceration over left forearm, mild concussion',
    triagePriority: 'yellow',
    vitals: {
      systolicBp: 120,
      diastolicBp: 80,
      heartRate: 84,
      spO2: 98,
      respiratoryRate: 18,
      temperature: 36.8,
      consciousLevel: 'alert',
      recordedAt: '2026-09-15T11:45:00Z',
    },
    arrivalTime: '2026-09-15T11:45:00Z',
    status: 'TRIAGED',
  },
];

// =========================================================================
// 4. HOSPITAL BLOOD BANK STOCK (THIS FACILITY ONLY)
// =========================================================================

export const INITIAL_HOSPITAL_BLOOD_STOCK: HospitalBloodStock[] = [
  { bloodGroup: 'O+', unitsAvailable: 14, bufferThreshold: 10, status: 'OPTIMAL', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'O-', unitsAvailable: 2, bufferThreshold: 4, status: 'LOW', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'A+', unitsAvailable: 11, bufferThreshold: 8, status: 'OPTIMAL', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'A-', unitsAvailable: 1, bufferThreshold: 3, status: 'CRITICAL_OUT', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'B+', unitsAvailable: 16, bufferThreshold: 8, status: 'OPTIMAL', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'B-', unitsAvailable: 3, bufferThreshold: 3, status: 'OPTIMAL', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'AB+', unitsAvailable: 6, bufferThreshold: 4, status: 'OPTIMAL', lastUpdated: '2026-09-15T08:00:00Z' },
  { bloodGroup: 'AB-', unitsAvailable: 0, bufferThreshold: 2, status: 'CRITICAL_OUT', lastUpdated: '2026-09-15T08:00:00Z' },
];

// =========================================================================
// 5. INITIAL FACILITY DISCHARGE RECORDS (CARE-CONTINUITY LOOP)
// =========================================================================

export const INITIAL_FACILITY_DISCHARGE_RECORDS: FacilityDischargeRecord[] = [
  {
    id: 'dis-001',
    referralId: 'ref-104',
    patientId: 'pat-004',
    patientName: 'Master Arjun Sanjay Chavan',
    patientAbha: '76-3391-4455-6677',
    dischargeDiagnosis: 'Severe Dehydration secondary to Acute Viral Enteritis (Resolved)',
    treatmentGiven: 'IV Ringer Lactate resuscitation, Zinc supplementation for 14 days, oral rehydration therapy',
    proceduresPerformed: ['Peripheral IV Cannulation', 'Pediatric Electrolyte Panel', 'Stool Hanging Drop (Negative)'],
    dischargeMedications: [
      { medicineName: 'Zinc Sulfate Syrup (20mg/5mL)', dosage: '5mL once daily', frequency: '1-0-0', durationDays: 14, instructions: 'Give after food' },
      { medicineName: 'Oral Rehydration Salts (ORS)', dosage: '1 sachet in 1L water', frequency: 'As needed', durationDays: 3, instructions: 'Continue after each loose stool' },
    ],
    patientCondition: 'IMPROVED',
    followUpDate: '2026-09-20',
    referBackFacilityId: 'fac-phc-nasrapur',
    referBackFacilityName: 'Nasrapur Primary Health Centre (PHC)',
    ashaWorkerName: 'Smt. Rekha Gaikwad',
    ashaWorkerPhone: '9822019286',
    followUpInstructions: 'Review weight and hydration status with ASHA / PHC Medical Officer on Day 5. Watch for fever or vomiting recurrence.',
    warningSigns: 'Lethargy, sunken eyes, inability to drink fluids, blood in stool.',
    dischargedAt: '2026-09-14T16:00:00Z',
    dischargedByDoctorName: 'Dr. Ananya Kulkarni',
    dischargedByDoctorId: 'user-spec-01',
    assignedBedFreed: 'GEN-F-01',
  },
];
