// Shared staff registry — importable from both server API routes and client components.
// Extracted from AuthContext.tsx to avoid 'use client' module boundary issues with Turbopack.

import { Role, UserProfile } from '@/lib/types';

export const PRE_REGISTERED_STAFF: Record<string, UserProfile> = {
  // ==========================================
  // 1. ASHA / FIELD LEVEL
  // ==========================================
  '9822019284': {
    id: 'user-asha-01',
    name: 'Smt. Sunita Shinde',
    role: 'asha',
    roleTitleEn: 'ASHA Facilitator (Ambavane)',
    roleTitleMr: 'आशा गट प्रवर्तक / सेविका (आंबवणे)',
    phone: '9822019284',
    facilityId: 'fac-sc-ambavane',
    facilityName: 'Ambavane Sub-Centre (Velhe PHC)',
    facilityType: 'Sub-Centre',
    hfrCode: 'HFR-MH-PUN-00412',
    taluka: 'Velhe',
    district: 'Pune',
    state: 'Maharashtra',
    village: 'Ambavane',
    registrationNumber: 'ASHA-MH-PUN-0941',
    administrativeLevel: 'field',
    permissions: ['view_basic_demographics', 'create_referral', 'register_patient'],
  },
  '9822019285': {
    id: 'user-asha-02',
    name: 'Smt. Meena Jadhav',
    role: 'asha',
    roleTitleEn: 'ASHA Worker (Pasali Ward)',
    roleTitleMr: 'आशा सेविका (पासली प्रभाग)',
    phone: '9822019285',
    facilityId: 'fac-sc-pasali',
    facilityName: 'Pasali Sub-Centre (Velhe PHC)',
    facilityType: 'Sub-Centre',
    hfrCode: 'HFR-MH-PUN-00413',
    taluka: 'Velhe',
    district: 'Pune',
    state: 'Maharashtra',
    village: 'Pasali',
    registrationNumber: 'ASHA-MH-PUN-0942',
    administrativeLevel: 'field',
    permissions: ['view_basic_demographics', 'create_referral', 'register_patient'],
  },
  '9822019286': {
    id: 'user-asha-03',
    name: 'Smt. Rekha Gaikwad',
    role: 'asha',
    roleTitleEn: 'ASHA Worker (Khed Shivapur Sector)',
    roleTitleMr: 'आशा सेविका (खेड शिवापूर विभाग)',
    phone: '9822019286',
    facilityId: 'fac-sc-khedshivapur',
    facilityName: 'Khed Shivapur Sub-Centre (Nasrapur PHC)',
    facilityType: 'Sub-Centre',
    hfrCode: 'HFR-MH-PUN-00414',
    taluka: 'Bhor',
    district: 'Pune',
    state: 'Maharashtra',
    village: 'Khed Shivapur',
    registrationNumber: 'ASHA-MH-PUN-0943',
    administrativeLevel: 'field',
    permissions: ['view_basic_demographics', 'create_referral', 'register_patient'],
  },
  '9822019287': {
    id: 'user-asha-04',
    name: 'Smt. Anita Kamble',
    role: 'asha',
    roleTitleEn: 'ASHA Worker (Kasurdi Sector)',
    roleTitleMr: 'आशा सेविका (कासूर्डी विभाग)',
    phone: '9822019287',
    facilityId: 'fac-sc-kasurdi',
    facilityName: 'Kasurdi Sub-Centre (Nasrapur PHC)',
    facilityType: 'Sub-Centre',
    hfrCode: 'HFR-MH-PUN-00415',
    taluka: 'Bhor',
    district: 'Pune',
    state: 'Maharashtra',
    village: 'Kasurdi',
    registrationNumber: 'ASHA-MH-PUN-0944',
    administrativeLevel: 'field',
    permissions: ['view_basic_demographics', 'create_referral', 'register_patient'],
  },

  // ==========================================
  // 2. PHC LEVEL
  // ==========================================
  '9422018374': {
    id: 'user-phc-01',
    name: 'Dr. Rajesh Deshmukh',
    role: 'phc_doctor',
    roleTitleEn: 'Medical Officer (MBBS) - Velhe PHC',
    roleTitleMr: 'वैद्यकीय अधिकारी (प्रा.आ.के. वेल्हे)',
    phone: '9422018374',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe Primary Health Centre (PHC)',
    facilityType: 'PHC',
    hfrCode: 'HFR-MH-PUN-00089',
    taluka: 'Velhe',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MMC-2014/08/3412',
    administrativeLevel: 'facility',
    assignedPatientIds: ['pat-001', 'pat-002'],
    permissions: [
      'view_basic_demographics',
      'view_clinical_reports',
      'edit_clinical_records',
      'create_referral',
      'emergency_break_glass',
      'register_patient',
    ],
  },
  '9822055555': {
    id: 'user-nurse-01',
    name: 'Sister Anita Jagtap',
    role: 'nurse',
    roleTitleEn: 'Staff Nurse (GNM) - Velhe PHC',
    roleTitleMr: 'परिचारिका (प्रा.आ.के. वेल्हे)',
    phone: '9822055555',
    facilityId: 'fac-phc-velhe',
    facilityName: 'Velhe Primary Health Centre (PHC)',
    facilityType: 'PHC',
    hfrCode: 'HFR-MH-PUN-00089',
    taluka: 'Velhe',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MNC-2016/04/1109',
    administrativeLevel: 'facility',
    permissions: [
      'view_basic_demographics',
      'view_clinical_reports',
      'emergency_break_glass',
      'register_patient',
    ],
  },
  '9422019999': {
    id: 'user-phc-02',
    name: 'Dr. Suresh Patil',
    role: 'phc_doctor',
    roleTitleEn: 'Medical Officer (MBBS) - Nasrapur PHC',
    roleTitleMr: 'वैद्यकीय अधिकारी (प्रा.आ.के. नसरापूर)',
    phone: '9422019999',
    facilityId: 'fac-phc-nasrapur',
    facilityName: 'Nasrapur Primary Health Centre (PHC)',
    facilityType: 'PHC',
    hfrCode: 'HFR-MH-PUN-00104',
    taluka: 'Bhor',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MMC-2017/05/2198',
    administrativeLevel: 'facility',
    assignedPatientIds: ['pat-003', 'pat-004', 'pat-005'],
    permissions: [
      'view_basic_demographics',
      'view_clinical_reports',
      'edit_clinical_records',
      'create_referral',
      'emergency_break_glass',
      'register_patient',
    ],
  },
  '9822066666': {
    id: 'user-pharm-01',
    name: 'Shri Anand Kadam',
    role: 'pharmacist',
    roleTitleEn: 'Pharmacist (B.Pharm) - Nasrapur PHC',
    roleTitleMr: 'औषध निर्माण अधिकारी (प्रा.आ.के. नसरापूर)',
    phone: '9822066666',
    facilityId: 'fac-phc-nasrapur',
    facilityName: 'Nasrapur Primary Health Centre (PHC)',
    facilityType: 'PHC',
    hfrCode: 'HFR-MH-PUN-00104',
    taluka: 'Bhor',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MSPC-2019/12/8762',
    administrativeLevel: 'facility',
    permissions: [
      'view_basic_demographics',
      'view_prescriptions_only',
    ],
  },

  // ==========================================
  // 3. DISTRICT LEVEL
  // ==========================================
  '9823091824': {
    id: 'user-dist-admin-01',
    name: 'Dr. Vinod Chavan',
    role: 'district_officer',
    roleTitleEn: 'District Health Officer (DHO) & District Medicals Coordinator',
    roleTitleMr: 'जिल्हा आरोग्य अधिकारी व औषध नियंत्रण (पुणे)',
    phone: '9823091824',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    facilityType: 'District Hospital',
    hfrCode: 'HFR-MH-PUN-00001',
    taluka: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MMC-2005/03/0762',
    administrativeLevel: 'district',
    permissions: [
      'view_basic_demographics',
      'view_aggregate_analytics',
    ],
  },
  '9823091823': {
    id: 'user-spec-01',
    name: 'Dr. Ananya Kulkarni',
    role: 'specialist',
    roleTitleEn: 'Chief Casualty & Triage Specialist (MD)',
    roleTitleMr: 'कॅज्युअल्टी व ट्रायज प्रमुख तज्ज्ञ (जिल्हा रुग्णालय औंध, पुणे)',
    phone: '9823091823',
    facilityId: 'fac-dh-pune',
    facilityName: 'District Hospital Aundh, Pune',
    facilityType: 'District Hospital',
    hfrCode: 'HFR-MH-PUN-00001',
    taluka: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    registrationNumber: 'MMC-2010/04/1890',
    administrativeLevel: 'district',
    assignedPatientIds: [],
    permissions: [
      'view_basic_demographics',
      'view_clinical_reports',
      'manage_admissions',
      'emergency_break_glass',
      'view_aggregate_analytics',
      'register_patient',
    ],
  },
  '9823091825': {
    id: 'user-spec-02',
    name: 'Dr. Snehal More',
    role: 'specialist',
    roleTitleEn: 'Specialist Doctor / Obstetrician (MS OB-GYN)',
    roleTitleMr: 'वरिष्ठ स्त्रीरोग व प्रसूती तज्ज्ञ (जिल्हा रुग्णालय नाशिक)',
    phone: '9823091825',
    facilityId: 'fac-dh-nashik',
    facilityName: 'District Civil Hospital, Nashik',
    facilityType: 'District Hospital',
    hfrCode: 'HFR-MH-NSK-00001',
    taluka: 'Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    registrationNumber: 'MMC-2012/07/2234',
    administrativeLevel: 'district',
    assignedPatientIds: [],
    permissions: [
      'view_basic_demographics',
      'view_clinical_reports',
      'manage_admissions',
      'emergency_break_glass',
      'view_aggregate_analytics',
      'register_patient',
    ],
  },
  '9823091826': {
    id: 'user-dist-admin-02',
    name: 'Shri Sachin Gite',
    role: 'district_officer',
    roleTitleEn: 'District Medicals & Resource Coordinator - Nashik',
    roleTitleMr: 'जिल्हा औषध व रुग्णालय संसाधन समन्वयक (नाशिक)',
    phone: '9823091826',
    facilityId: 'fac-dh-nashik',
    facilityName: 'District Civil Hospital, Nashik',
    facilityType: 'District Hospital',
    hfrCode: 'HFR-MH-NSK-00001',
    taluka: 'Nashik',
    district: 'Nashik',
    state: 'Maharashtra',
    registrationNumber: 'DHM-2018/11/4501',
    administrativeLevel: 'district',
    permissions: [
      'view_basic_demographics',
      'view_aggregate_analytics',
    ],
  },
};

export const USER_PROFILES_BY_ROLE: Record<Role, UserProfile> = {
  asha: PRE_REGISTERED_STAFF['9822019284'],
  phc_doctor: PRE_REGISTERED_STAFF['9422018374'],
  nurse: PRE_REGISTERED_STAFF['9822055555'],
  pharmacist: PRE_REGISTERED_STAFF['9822066666'],
  specialist: PRE_REGISTERED_STAFF['9823091823'],
  district_officer: PRE_REGISTERED_STAFF['9823091824'],
};

export const ALL_REGISTERED_USERS: UserProfile[] = Object.values(PRE_REGISTERED_STAFF);

export function findUserById(userId: string): UserProfile | undefined {
  return ALL_REGISTERED_USERS.find((u) => u.id === userId || u.phone === userId);
}

export const GUEST_PROFILE: UserProfile = {
  id: 'guest-unauthenticated',
  name: 'Unauthenticated Session',
  role: 'asha',
  roleTitleEn: 'Guest Session',
  roleTitleMr: 'अनोळखी सत्र',
  phone: '',
  facilityId: '',
  facilityName: 'Public Health Department, Maharashtra',
  facilityType: 'PHC',
  hfrCode: 'HFR-UNASSIGNED',
  taluka: '',
  district: '',
  registrationNumber: '',
  administrativeLevel: 'facility',
  permissions: [],
};
